ARG miniconda_version=4.9.2
FROM continuumio/miniconda3:${miniconda_version}

ARG userid="31415"
ARG groupid="31415"

# In the *container*
#   Note that a matching group is added automatically
RUN addgroup --gid ${groupid} lig && \
    adduser lig --uid ${userid} --gid ${groupid} \
    --gecos '' --disabled-password

# Additional quality-of-life packages and SNMP stuff
#   Add the non-free repository first so we can get the nonfree MIBs
#
# Should find out a way to just get the debian release version automagically
#
RUN DEBIAN_RELEASE=bullseye && \
    # Adding non-free repo for netperf
    echo "deb http://deb.debian.org/debian ${DEBIAN_RELEASE} non-free" > \
        /etc/apt/sources.list.d/debian-non-free.list && \
    apt-get -qq update && \
    apt-get -y install snmp libsnmp-dev snmp-mibs-downloader \
                       libffi-dev smitools libsmi2-dev \
                       vim build-essential gcc vim rsync wget \
                       procps libgl1

# Copy in the lists of stuff that Conda and pip need to install
#   (./ is relative to WORKDIR)
COPY --chown=lig:lig ./dockerfiles/pip_install.txt ./
COPY --chown=lig:lig ./dockerfiles/conda_install.txt ./
COPY --chown=lig:lig ./dockerfiles/condaforge_install.txt ./

# One layer each for the conda and pip installs
# These need to happen in this specific order to actually work
RUN conda install -y --file conda_install.txt
RUN conda install -c conda-forge --file condaforge_install.txt
RUN pip install --no-cache-dir -r pip_install.txt

USER lig
RUN mkdir /home/lig/.snmp && mkdir /home/lig/.snmp/mibs
# NOTE: THis means I have to copy in the MIBS at runtime
# COPY --chown=lig:lig ../mibs/* /home/lig/.snmp/mibs/

# At this point it's a minimal working LIG python image
#   so copy in the LIG codes and get them going
USER lig:lig
WORKDIR /home/lig/
RUN mkdir conf && mkdir logs && mkdir Codes

# Install the ligmos library, for all users.
#   This is designed to be called from the base ligmos dir already, so
#   copy over the contents and put it in a subdirectory in the image
WORKDIR /home/lig/Codes/
RUN mkdir ligmos
COPY --chown=lig:lig ./ ligmos/
WORKDIR /home/lig/Codes/ligmos

# Totally unnecessary root install but whatever
USER root
RUN pip install -e .

# Dump us into an iPython shell if there's no
#   actual command issued to start a LIG code
USER lig
WORKDIR /home/lig/
CMD ["ipython"]
